Sample_project/src/objects/Bloom__c.object
<CustomObject>
    <fields>
        <fullName>Bouquet__c</fullName>
        <label>Bouquet</label>
        <referenceTo>Bouquet__c</referenceTo>
        <relationshipLabel>Blooms</relationshipLabel>
        <relationshipName>Blooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flower__c</fullName>
        <label>Flower</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Blooms</relationshipLabel>
        <relationshipName>Blooms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Bloom</label>
    <nameField>
        <displayFormat>BL-{00000000}</displayFormat>
        <label>Bloom Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Sample_project/src/objects/Bouquet__c.object
<CustomObject>
    <label>Bouquet</label>
    <nameField>
        <displayFormat>B-{00000000}</displayFormat>
        <label>Bouquet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bouquets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Sample_project/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <label>Color</label>
        <picklist>
            <picklistValues>
                <fullName>Blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lavender</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pink</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>HTML_Color_Code__c</fullName>
        <formula>CASE(Color__c 

,&apos;Blue&apos; 
,&apos;#0000FF&apos; 

,&apos;Green&apos;
,&apos;#008000&apos;

,&apos;Lavender&apos;
,&apos;#E6E6FA&apos;

,&apos;Orange&apos;
,&apos;#FFA500&apos;

,&apos;Pink&apos;
,&apos;#FFC0CB&apos;

,&apos;Purple&apos;
,&apos;#800080&apos;

,&apos;Red&apos;
,&apos;#FF0000&apos;

,&apos;Yellow&apos;
,&apos;#FFFF00&apos;

,&apos;White&apos;
,&apos;#FFFFFF&apos;

,&apos;#000000&apos;

)</formula>
        <label>HTML Color Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inventory_Remaining__c</fullName>
        <formula>Initial_Inventory__c - Inventory_Used__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inventory Remaining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory_Used__c</fullName>
        <label>Inventory Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Sample_project/src/classes/QueryUtilityClass.cls
/******************************************************************************************************************************
* @class name      : QueryUtilityClass
* @description     : This class is used for Retruning
*                       1. Query for products to be displayed on screen.
*                       2. Query Blooms of a specified Bouquet. 
* @test class      : BloomTriggerHandlerTest            
* @author          : Candidate
* @date            : 22/09/2016            
                    
* Modification Log :
* -----------------------------------------------------------------------------------------------------------------
* Developer                                      Date(MM/DD/YYYY)       Description
* -----------------------------------------------------------------------------------------------------------------
* Candidate                                      22/09/2016             Created.

******************************************************************************************************************************/

public class QueryUtilityClass {
        
    //This method is used to retrieve Item records from Product2 Object
    //based on the bouquetId and selectedCategory provided
    public static List<Product2> getProductRecords(String bouquetId, String selectedCategory) {
        
        String query = '';
        String categoryFilter = '';
        String sortingClause = '';
        String finalQuery = '';
        List<Id> listFlowerId=new List<Id>();
        
        // Retrieving Flower Ids for edit scenarios. It will contain inactive Product as well
        // If it is being utilised by underlying bouquet previously.
        for(Bloom__c b:[SELECT Flower__c FROM Bloom__c WHERE Bouquet__c =: bouquetId]){
            listFlowerId.add(b.Flower__c);
        }
        
        query = 'Select Id,Name,Family,HTML_Color_Code__c,Inventory_Remaining__c,Inventory_Used__c,IsActive,Color__c, Cost__c '+
                        ' From Product2 ';
        
        
        if(bouquetId == null){
           query  += ' WHERE IsActive = TRUE ';
        }
        else{
           query  += ' WHERE (IsActive = TRUE OR Id IN: listFlowerId) ';
        }
        
        // If category filter is selected then query will be formed in such a way that it retrieves
        // only those Products(Flowers) records where particular category is selected
        if(String.isNotBlank(selectedCategory) && !selectedCategory.equalsIgnoreCase('--Any Type--')){
            categoryFilter = ' Family = \'' + selectedCategory+ '\'';
                query +=' AND ' + categoryFilter;   
            
        }
        
        // this sorting clause is used to sort records based on the 
        // Cost and further with Color. 
        sortingClause = ' ORDER BY Cost__c, Color__c ASC ';
        
        finalQuery = query + sortingClause;
        
        return Database.Query(finalQuery);
    }
    
    // This method is used to return Bloom Record on Bloom__c Object
    // based on the bouquetId record Id provided
    public static List<Bloom__c> getBloomRecords(Id bouquetId) {
       List<Bloom__c> bloomRecordsList = [SELECT Id,Name,Quantity__c,Flower__c,
                                            Bouquet__c from Bloom__c where Flower__c != null
                                            AND Bouquet__c = : bouquetId  
                                            Limit : Limits.getLimitQueryRows()];
        return bloomRecordsList;
    }  

}